from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime
from .common import GeoLocation

class CurrencyAnalysis(BaseModel):
    cvScore: float = Field(..., ge=0.0, le=100.0, description="Local CNN model verification score")
    isCounterfeit: bool = Field(..., description="True if marked as counterfeit, False if authentic")
    confidenceScore: float = Field(..., ge=0.0, le=100.0, description="Overall confidence percentage")
    anomaliesDetected: List[str] = Field(default_factory=list, description="Visual markers missing or falsified")
    geminiRemarks: Optional[str] = Field(None, description="Analysis explanations generated by Gemini API")

class CurrencyScan(BaseModel):
    scanId: str = Field(..., description="Unique Scan identifier")
    scannedBy: str = Field(..., description="UID of analyst scanning")
    imageStoragePath: str = Field(..., description="Storage bucket path, e.g., currency/SCAN_777.png")
    imageUrl: str = Field(..., description="Signed download URL of note image")
    serialNumber: Optional[str] = Field(None, description="Banknote serial number extracted")
    denomination: int = Field(..., description="Denomination, e.g. 500, 200, 2000")
    analysis: CurrencyAnalysis
    location: Optional[GeoLocation] = None
    createdAt: datetime = Field(default_factory=datetime.utcnow)
